-- Migration 005 - Bairros oficiais de Campo Grande / MS.
--
-- Cada bairro entra no padrão "Bairro/Região Urbana" (ex.: Amambaí/Centro),
-- somando-se aos que já existiam. A tela de Nova Reunião também deixa digitar
-- um bairro novo na hora, então esta lista é o ponto de partida, não um teto.

INSERT INTO regioes (nome) VALUES
  -- Centro
  ('Amambaí/Centro'),
  ('Bela Vista/Centro'),
  ('Cabreúva/Centro'),
  ('Centro/Centro'),
  ('Cruzeiro/Centro'),
  ('Glória/Centro'),
  ('Itanhangá/Centro'),
  ('Jardim dos Estados/Centro'),
  ('Monte Líbano/Centro'),
  ('Planalto/Centro'),
  ('Santa Fé/Centro'),
  ('São Bento/Centro'),
  ('São Francisco/Centro'),
  -- Anhanduizinho
  ('Aero Rancho/Anhanduizinho'),
  ('Alves Pereira/Anhanduizinho'),
  ('Centenário/Anhanduizinho'),
  ('Guanandi/Anhanduizinho'),
  ('Jardim Paulista/Anhanduizinho'),
  ('Jockey Club/Anhanduizinho'),
  ('Los Angeles/Anhanduizinho'),
  ('Parati/Anhanduizinho'),
  ('Piratininga/Anhanduizinho'),
  ('Pioneiros/Anhanduizinho'),
  -- Bandeira
  ('Autonomista/Bandeira'),
  ('Carandá/Bandeira'),
  ('Chácara Cachoeira/Bandeira'),
  ('Jardim Veraneio/Bandeira'),
  ('Rita Vieira/Bandeira'),
  ('Tiradentes/Bandeira'),
  ('TV Morena/Bandeira'),
  ('Universitário/Bandeira'),
  ('Vilas Boas/Bandeira'),
  -- Prosa
  ('Carandá Bosque/Prosa'),
  ('Chácara dos Poderes/Prosa'),
  ('Cidade Jardim/Prosa'),
  ('Mata do Jacinto/Prosa'),
  ('Nasser/Prosa'),
  ('Novos Estados/Prosa'),
  ('Veraneio/Prosa'),
  -- Segredo
  ('Coronel Antonino/Segredo'),
  ('José Abrão/Segredo'),
  ('Mata do Segredo/Segredo'),
  ('Monte Castelo/Segredo'),
  ('Nova Lima/Segredo'),
  ('Santo Amaro/Segredo'),
  ('Seminário/Segredo'),
  ('São Conrado/Segredo'),
  ('Sobrinho/Segredo'),
  -- Imbirussu
  ('Caiobá/Imbirussu'),
  ('Coophavila II/Imbirussu'),
  ('Dr. Albuquerque/Imbirussu'),
  ('Indubrasil/Imbirussu'),
  ('Jardim Carioca/Imbirussu'),
  ('José Tavares/Imbirussu'),
  ('Nova Campo Grande/Imbirussu'),
  ('Núcleo Industrial/Imbirussu'),
  ('Popular/Imbirussu'),
  -- Lagoa
  ('Batistão/Lagoa'),
  ('Caiçara/Lagoa'),
  ('Centro Oeste/Lagoa'),
  ('Estrela Dalva/Lagoa'),
  ('Leblon/Lagoa'),
  ('Maria Aparecida Pedrossian/Lagoa'),
  ('Moreninhas/Lagoa'),
  ('Noroeste/Lagoa'),
  ('Panamá/Lagoa'),
  ('Santo Antônio/Lagoa'),
  ('Tarumã/Lagoa'),
  ('Taquarussu/Lagoa'),
  ('Tijuca/Lagoa'),
  ('União/Lagoa');
